"""Initial Migration

Revision ID: 197b4c6d4d41
Revises: 
Create Date: 2023-03-08 12:33:59.459397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197b4c6d4d41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppy',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppy')
    # ### end Alembic commands ###
